// pio-project/src/arm_mega/keyframes.h
// ----------------------------------------------------------------------
// Auto-generated by scripts/record_keyframes.py on 2026-06-11 21:22:05.
// Re-run the script to recapture, or edit the values below by hand
// (the struct layout is base, shoulder, elbow, claw).
// ----------------------------------------------------------------------
#pragma once
#include <stdint.h>

struct Pose {
    uint8_t base;
    uint8_t shoulder;
    uint8_t elbow;
    uint8_t claw;
};

// Sentinel: a keyframe whose base == BASE_KEEP leaves the base target
// untouched when applied — the grasp+drop sequence uses it to preserve the
// visually-servoed base through the pickup phase. 255 is outside LIM_BASE.
static constexpr uint8_t BASE_KEEP = 255;

// Home pose — must match LIM_*.initial in main.cpp.
static constexpr Pose KF_HOME {  90,  36,  55,   5 };

// ---- Pickup sequence (legacy 'p': full home -> pick -> drop -> home) ------
static constexpr Pose KF_APPROACH    {       142,  30, 113,  21 };
static constexpr Pose KF_GRASP_DOWN  {       142,  30, 113,  21 };
static constexpr Pose KF_GRASP_CLOSE {       142,  30, 113,  21 };
static constexpr Pose KF_LIFT        {       142,  30, 113,  21 };
static constexpr Pose KF_DROP_OVER   {       142,  30, 113,  21 };
static constexpr Pose KF_DROP_RELEASE {       142,  30, 113,  21 };

static constexpr Pose PICKUP_SEQUENCE[] = {
    KF_HOME,
    KF_APPROACH,
    KF_GRASP_DOWN,
    KF_GRASP_CLOSE,
    KF_LIFT,
    KF_DROP_OVER,
    KF_DROP_RELEASE,
    KF_HOME,
};
static constexpr uint8_t PICKUP_SEQUENCE_LEN =
    sizeof(PICKUP_SEQUENCE) / sizeof(PICKUP_SEQUENCE[0]);

// ---- Grasp + drop sequence (USB 'g': run from the servoed HOVER pose) -----
// Pickup-phase keyframes carry base == BASE_KEEP so the servoed alignment is
// preserved; the drop phase snaps the base to the recorded drop-zone angle.
// KF_GD_LIFT MUST tuck the elbow (>= ELBOW_LIFT_SAFE_DEG) or the shoulder
// lift interlock hangs the sequence — see main.cpp.
static constexpr Pose KF_GD_DESCEND  { BASE_KEEP, 110,  33,  10 };
static constexpr Pose KF_GD_CLOSE    { BASE_KEEP, 110,  33,  45 };
static constexpr Pose KF_GD_LIFT_FOLD { BASE_KEEP, 110, 175,  45 };
static constexpr Pose KF_GD_LIFT_UP  { BASE_KEEP,  46, 175,  48 };
static constexpr Pose KF_GD_LIFT     { BASE_KEEP,  46,  53,  48 };
static constexpr Pose KF_GD_SWING    {       180,  46,  53,  47 };
static constexpr Pose KF_GD_DROPDN   {       180,  92,  12,  44 };
static constexpr Pose KF_GD_RELEASE  {       180,  92,  12,   8 };
static constexpr Pose KF_GD_LIFTOUT_FOLD {       180,  92, 175,   8 };
static constexpr Pose KF_GD_LIFTOUT_UP {       180,  40, 175,   7 };
static constexpr Pose KF_GD_LIFTOUT  {        79,  40,  54,   7 };

static constexpr Pose GRASP_DROP_SEQUENCE[] = {
    KF_GD_DESCEND,
    KF_GD_CLOSE,
    KF_GD_LIFT_FOLD,
    KF_GD_LIFT_UP,
    KF_GD_LIFT,
    KF_GD_SWING,
    KF_GD_DROPDN,
    KF_GD_RELEASE,
    KF_GD_LIFTOUT_FOLD,
    KF_GD_LIFTOUT_UP,
    KF_GD_LIFTOUT,
};
static constexpr uint8_t GRASP_DROP_SEQUENCE_LEN =
    sizeof(GRASP_DROP_SEQUENCE) / sizeof(GRASP_DROP_SEQUENCE[0]);
