// arm_mega/main.cpp
// ----------------------------------------------------------------------
// Runs on the Elegoo Mega 2560 R3 mounted on the arm base.
//
// Responsibilities:
//   1. Receive 7-byte framed packets from the HC-05 (paired as SLAVE)
//      on Serial1 at 9600 baud.
//   2. Rate-limit commanded angles into smooth servo motion (slew).
//   3. Fail-safe: if no valid frame for LINK_TIMEOUT_MS, freeze in place.
//
// Vision lives on the Raspberry Pi side now (Logitech C270 + OpenCV in
// vision/colour_detect.py). The Mega has no on-board camera link.
//
// Wiring (Mega):
//   HC-05  VCC  -> 5V
//   HC-05  GND  -> GND
//   HC-05  TXD  -> Mega D19  (RX1)           [HC-05 TX is 3.3V-ish, Mega accepts]
//   HC-05  RXD  -> Mega D18  (TX1) via divider (see wiring guide)
//   Servos     : see SERVO_PIN_* below. Power from external 4xAA pack,
//                NOT from the Mega's 5V rail. Share GND with the Mega.
//
// IMPORTANT — pin choice on Mega:
//   The Servo library on Mega supports servos on ANY digital pin (unlike
//   the Uno). D9/10/11 are fine; D6 is used for the claw to keep lines
//   away from the SPI header in case we add sensors later.
// ----------------------------------------------------------------------

#include <Arduino.h>      // Core Arduino types/functions (millis(), Serial, etc.)
#include <Servo.h>        // Standard Arduino Servo library — generates the PWM
                          // pulse train that an MG996R expects (1.0..2.0 ms
                          // pulse every ~20 ms, mapped to 0..180 degrees).
#include <ArmProtocol.h>  // Our shared header in lib/ArmProtocol — defines the
                          // 7-byte packet format and the byte-by-byte decoder.
#include "keyframes.h"    // Pickup-sequence poses. Generated by
                          // scripts/record_keyframes.py — placeholder
                          // (all-HOME) is checked in so the build works
                          // before you've recorded.

// ---- Pin assignments ------------------------------------------------
// Which Mega digital pin each servo's signal wire is connected to. Change
// these here ONLY if you re-route the wiring; the rest of the code reads
// these constants instead of hard-coded numbers, so you don't have to hunt
// through the file. (`static constexpr uint8_t` = compile-time constant,
// 1 byte, file-local — the C++ way to say "#define a small integer".)
static constexpr uint8_t SERVO_PIN_BASE     = 9;
static constexpr uint8_t SERVO_PIN_SHOULDER = 7;
static constexpr uint8_t SERVO_PIN_ELBOW    = 11;
static constexpr uint8_t SERVO_PIN_CLAW     = 6;

// ---- E-stop rocker switch -------------------------------------------
// A rocker switch between this pin and GND, read with the internal pull-up.
// Wired fail-safe: the switch is CLOSED (pin pulled to GND, LOW) in the RUN
// position, OPEN (pin floats HIGH) in the E-STOP position — so a broken wire
// also reads HIGH and trips the stop. ESTOP_ENGAGED_LEVEL is the pin level
// that means "stopped"; flip it to LOW if your rocker is wired the other way.
static constexpr uint8_t ESTOP_PIN            = 2;
static constexpr uint8_t ESTOP_ENGAGED_LEVEL  = HIGH;
// Engaging is instant (safety); clearing must hold the RUN level this long to
// debounce contact bounce so the arm doesn't flicker back to life.
static constexpr uint32_t ESTOP_CLEAR_DEBOUNCE_MS = 50;

// ---- Motion limits --------------------------------------------------
// Tune these AFTER mechanical bring-up — set the lower/upper so the arm
// cannot drive itself into its own frame. Start conservative.
//
// `Limits` bundles three numbers per joint:
//   lo      = lowest angle (degrees) we will ever command
//   hi      = highest angle we will ever command
//   initial = where the joint should sit at power-on (the "safe pose")
// Keeping them grouped means we can pass one struct around instead of
// three loose variables, and the compiler can inline the whole thing.
struct Limits { uint8_t lo, hi, initial; };
static constexpr Limits LIM_BASE     {  0, 180,  90 };
static constexpr Limits LIM_SHOULDER { 30, 155,  36 };
static constexpr Limits LIM_ELBOW    {  0, 180,  55 };
static constexpr Limits LIM_CLAW     {  5, 160,   5 };  // claw OPENS toward lo; home (5) = fully open

// ---- Hover pose -----------------------------------------------------
// Where the USB 'v' command parks the arm to hover over the pickup zone,
// before the Pi visual-servos the base onto the rock. SET shoulder/elbow/
// claw BY JOGGING the arm to a good hover (claw centred over the pickup
// zone, OPEN, at a safe height above the rock) and reading the live "[pos]"
// line off USB — exactly how HOME was set. The `base` field is IGNORED:
// 'v' deliberately leaves the base where it is so the servo loop can aim it
// (the field only exists to fill out the Pose struct). Kept here, NOT in
// keyframes.h, so record_keyframes.py can't overwrite it.
//
// Jogged on the rig 2026-06-10: claw open over the pickup zone at grasp-clear
// height. base (90) is ignored. NOTE: shoulder=97 sits in the stall zone
// (> SHOULDER_LIFT_GATE_DEG) with the elbow extended — this is the reach
// needed to get over the rock, but it's the high-torque cantilever pose, so
// watch for a shoulder stall / rail brown-out if it's held a long time during
// the base-servo loop. Raise the hover (lower shoulder angle / fold elbow) if
// it stalls.
static constexpr Pose HOVER { 90, 97, 28, 21 };

// Max angular speed per servo. 60 deg/s is well below MG996R stall current
// even at the shoulder's worst-case lever arm (arm fully extended), which
// reduces the chance of the motor losing sync with its commanded angle —
// the open-loop failure mode that triggered this slowdown. Same value for
// every joint so the arm behaves uniformly and is easier to drive/debug.
// This is what makes the arm move SMOOTHLY instead of snapping instantly
// to whatever angle the joystick last asked for — see slewAndWrite().
static constexpr float MAX_DEG_PER_SEC = 60.0f;

// ---- Shoulder lift interlock ----------------------------------------
// The shoulder servo stalls when it's driven down far enough to cantilever
// the forearm out horizontally: the lever arm — and so the gravity torque
// it must hold — peaks and exceeds the MG996R's stall torque (it "loses
// power" and can't lift back up until the load is taken off by hand).
//
// The fix is an interlock, not an override: the elbow stays fully under
// remote control the whole time (so you can work it to pick things up),
// but while the shoulder is down in the stall zone we REFUSE to let it
// move back UP until the elbow has been bent back far enough to pull the
// forearm's mass in and shrink the lever arm. We don't speed the elbow up
// or move it for you — we just pause the shoulder's upward commands until
// the elbow is tucked, then let them through. Lowering the shoulder and
// moving the elbow are never blocked.
//
// Active only when the shoulder is below (angle above) SHOULDER_LIFT_GATE_DEG.
// "Tucked enough to lift" means the elbow has reached ELBOW_LIFT_SAFE_DEG.
static constexpr uint8_t SHOULDER_LIFT_GATE_DEG = 80;    // shoulder angles above this interlock the lift
static constexpr uint8_t ELBOW_LIFT_SAFE_DEG    = 165;   // elbow must be tucked at least this far to lift
// Elbow angle the staged home folds to before lifting the shoulder out of
// the stall zone. A few degrees below the 180° hard stop, comfortably past
// ELBOW_LIFT_SAFE_DEG so the lift unlocks. See HomeState / homeTick().
static constexpr uint8_t HOME_FOLD_ELBOW_DEG    = 175;

// If we haven't seen a valid frame in this long, hold position.
// Acts as a safety net: if the BT link drops or the controller is
// switched off mid-motion, the arm freezes instead of running away.
static constexpr uint32_t LINK_TIMEOUT_MS = 500;

// Update tick — how often we re-compute slewed angles and write servos.
// 20 ms = 50 Hz. The Servo library refreshes pulses at ~50 Hz internally
// anyway, so going faster here would just waste CPU.
static constexpr uint32_t TICK_MS = 20;  // 50 Hz

// ---- Pickup-sequence tunables --------------------------------------
// How close each joint must be to a keyframe before we count as "arrived".
// 2° is well within MG996R repeatability and above one slew step
// (60°/s * 20 ms = 1.2°/tick) so we don't oscillate around the target.
static constexpr uint8_t  SEQ_TOLERANCE_DEG = 2;
// Hold each pose this long after arrival. Critical at GRASP_CLOSE /
// DROP_RELEASE — gives the gripper time to actually close/open before
// we slew off to the next keyframe.
static constexpr uint32_t SEQ_DWELL_MS      = 250;
// Tolerance for the "is the arm at home?" gate. Looser than the keyframe
// tolerance because manual homing is open-loop and the user might be a
// degree or two off after pressing 'h' on the controller.
static constexpr uint8_t  SEQ_HOME_TOL_DEG  = 5;
// Any axis moving by more than this between consecutive BT frames is
// treated as the user actively driving the joystick. Set to 0 so even a
// single degree of intentional input on the controller kicks the arm
// out of auto mode — the user wanted "any movement on the remote
// overrides auto". userIsDriving also OR's in the FLAG_BUTTON bit from
// the protocol to catch base-button taps and pot activity that may not
// register as an angle change between two consecutive frames.
// Safe because a truly parked controller emits identical frames (the
// joystick deadzone + pot arming gate suppress all numerical drift on
// the controller side, so maxDelta is genuinely 0 when nobody's
// touching it).
static constexpr uint8_t  SEQ_OVERRIDE_DEG  = 0;
// A real manual takeover must be SUSTAINED for this many consecutive driving
// frames before it kicks the arm out of auto mode / cancels a home / aborts a
// sequence. With SEQ_OVERRIDE_DEG = 0, a single degree of BT jitter reads as
// "driving"; without this debounce that transient noise knocks auto mode off
// the instant the Pi enables it (and stomps Pi-set targets), so home/hover
// never run. A genuine stick push lasts many frames; jitter is 1-2. At 50 Hz,
// 3 frames = 60 ms — well below human reaction, so manual override still feels
// instant, but isolated noise is ignored.
static constexpr uint8_t  MANUAL_OVERRIDE_FRAMES = 3;
// The controller is considered "idle" (no joystick movement) once this
// much time has passed since the last frame whose delta exceeded
// SEQ_OVERRIDE_DEG. Used to gate entry into auto mode — we refuse 'a' to
// turn auto ON unless the controller has been parked for this long, so
// you can't arm the arm while you're mid-stick-push.
static constexpr uint32_t CONTROLLER_IDLE_MS = 500;

// ---- State ----------------------------------------------------------
// Four Servo objects, one per joint. `Servo` is a class from <Servo.h>;
// declaring an object here reserves a slot in the library's internal
// table of active servos. We don't .attach() them until setup().
Servo servoBase, servoShoulder, servoElbow, servoClaw;

// One decoder instance that "owns" the 7-byte buffer for in-progress
// frames coming in from Serial1. Stateful: it remembers how many bytes
// of the next frame it has already seen.
ArmProto::Decoder decoder;

// One row per joint. Bundling per-axis info into a struct lets the rest
// of the code loop over `axes[]` instead of repeating the same logic
// four times. References (`Limits&`, `Servo&`) mean the struct points
// at the original objects — no copies, no risk of writing to a copy.
struct AxisState {
    float current;       // what we're actually commanding right now (slewed,
                         // float so we can move by fractional degrees per tick)
    uint8_t target;      // the latest angle the controller asked for
    const Limits& lim;   // motion limits for this joint (read-only)
    Servo& servo;        // the Servo object we write the pulse to
};

// Initialise each axis: start at the safe pose, target the safe pose
// (so we don't immediately move on boot), and bind the lim/servo refs.
AxisState axes[] = {
    { (float)LIM_BASE.initial,     LIM_BASE.initial,     LIM_BASE,     servoBase     },
    { (float)LIM_SHOULDER.initial, LIM_SHOULDER.initial, LIM_SHOULDER, servoShoulder },
    { (float)LIM_ELBOW.initial,    LIM_ELBOW.initial,    LIM_ELBOW,    servoElbow    },
    { (float)LIM_CLAW.initial,     LIM_CLAW.initial,     LIM_CLAW,     servoClaw     },
};

// Timestamps (milliseconds since boot, from millis()).
uint32_t lastFrameMs  = 0;   // when we last received a valid frame — fed the watchdog
uint32_t lastTickMs   = 0;   // when we last ran the slew/write step
uint32_t lastPosLogMs = 0;   // when we last printed servo positions

// ---- RX debug (TEMPORARY — diagnosing the controller "always driving" bug).
// Captures the last received frame + whether it read as "driving", and a
// per-interval frame/driving tally, dumped at 2 Hz as [rx] lines. Toggle with
// USB 'd'. Remove once the drift source is found.
static ArmProto::Frame g_lastRx { 0, 0, 0, 0, 0 };
static uint8_t  g_lastMaxDelta = 0;
static uint16_t g_rxCount      = 0;
static uint16_t g_drvCount     = 0;
static uint32_t g_lastRxDbgMs  = 0;
static bool     g_rxDebug      = true;

// ---------------------------------------------------------------------
// Squash a value into the [lo, hi] range. `inline` hints the compiler to
// paste the body at each call site (cheap, the function is tiny).
static inline uint8_t clampTo(uint8_t v, const Limits& l) {
    if (v < l.lo) return l.lo;
    if (v > l.hi) return l.hi;
    return v;
}

// ---------------------------------------------------------------------
// Pickup-sequence runner state + helpers.
// IDLE: nothing happening, manual control as normal.
// MOVING: slewing toward PICKUP_SEQUENCE[seqIndex].
// DWELLING: arrived at that keyframe, holding for SEQ_DWELL_MS before
//           advancing to the next one.
// ---------------------------------------------------------------------
enum class SeqState : uint8_t { IDLE, MOVING, DWELLING };
static SeqState seqState     = SeqState::IDLE;

// ---- Staged home --------------------------------------------------------
// Homing straight to KF_HOME from the stall zone would try to lift the
// shoulder while the elbow is still extended — the lift interlock would veto
// it and the arm would hang half-homed. So when home is requested with the
// shoulder down, we sequence it: FOLD the elbow back, LIFT the shoulder out
// of the zone, then PLACE the elbow at its home angle. The claw is sent home
// throughout. Triggered by FLAG_HOME from the controller or the USB 'h'.
enum class HomeState : uint8_t { IDLE, FOLD, LIFT, PLACE };
static HomeState homeState   = HomeState::IDLE;
static uint8_t  seqIndex     = 0;            // index into the active sequence[]
static uint32_t seqEnteredMs = 0;            // millis() when current state began

// The sequence runner can walk either the canned PICKUP_SEQUENCE (USB 'p',
// home->pick->drop->home) or the GRASP_DROP_SEQUENCE (USB 'g', run from the
// servoed hover). Both share seqTick()/seqApplyKeyframe() via this pointer so
// there's one state machine, not two. Defaults to the pickup sequence.
static const Pose* activeSeq    = PICKUP_SEQUENCE;
static uint8_t     activeSeqLen = PICKUP_SEQUENCE_LEN;
static bool     seqAutoMode  = false;        // false = triggers are ignored
// millis() at the last frame whose delta exceeded SEQ_OVERRIDE_DEG.
// Updated by applyFrame() and read by controllerIdle() / the 'a' handler
// to enforce "can only enable auto mode while the controller is parked".
static uint32_t lastControllerMoveMs = 0;

// ---- E-stop state ---------------------------------------------------
// estopEngaged is the debounced "we are stopped" flag, read all over loop().
// When engaged the arm holds its current pose, opens the claw, and ignores
// every motion input (Bluetooth, USB, sequence, home) until the rocker is
// returned to RUN.
static bool     estopEngaged   = false;
static uint32_t estopRunSinceMs = 0;   // millis() since the pin last read RUN

// True iff the controller has been parked (no over-threshold motion) for
// CONTROLLER_IDLE_MS. Note this is also true at boot before any frame has
// arrived — that's intentional, you can arm auto mode before powering
// the controller on.
static inline bool controllerIdle() {
    return (millis() - lastControllerMoveMs) > CONTROLLER_IDLE_MS;
}

// Push PICKUP_SEQUENCE[i] into axes[].target and pet the BT watchdog so
// the link-timeout check in loop() doesn't snap targets back to current
// and freeze us mid-sequence.
static void seqApplyKeyframe(uint8_t i) {
    const Pose& kf = activeSeq[i];
    // base == BASE_KEEP means "hold the base wherever it is" — used by the
    // grasp+drop sequence to preserve the visually-servoed alignment.
    if (kf.base != BASE_KEEP)
        axes[0].target = clampTo(kf.base, axes[0].lim);
    axes[1].target = clampTo(kf.shoulder, axes[1].lim);
    axes[2].target = clampTo(kf.elbow,    axes[2].lim);
    axes[3].target = clampTo(kf.claw,     axes[3].lim);
    lastFrameMs = millis();
}

// All four joints within SEQ_TOLERANCE_DEG of their current target?
static bool seqAtTarget() {
    for (auto& a : axes) {
        int err = (int)a.target - (int)(a.current + 0.5f);
        if (err < 0) err = -err;
        if (err > SEQ_TOLERANCE_DEG) return false;
    }
    return true;
}

// All four joints within SEQ_HOME_TOL_DEG of KF_HOME? Used by the
// "only auto-trigger when parked at home" safety gate.
static bool seqAtHome() {
    auto near = [](float cur, uint8_t want) {
        int err = (int)(cur + 0.5f) - (int)want;
        if (err < 0) err = -err;
        return err <= SEQ_HOME_TOL_DEG;
    };
    return near(axes[0].current, KF_HOME.base)
        && near(axes[1].current, KF_HOME.shoulder)
        && near(axes[2].current, KF_HOME.elbow)
        && near(axes[3].current, KF_HOME.claw);
}

static void seqAbort(const __FlashStringHelper* why) {
    if (seqState == SeqState::IDLE) return;
    seqState = SeqState::IDLE;
    // Freeze in place: target = current, mirroring the BT-link watchdog.
    for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);
    Serial.print(F("[seq] abort: "));
    Serial.println(why);
}

static void seqStart() {
    if (seqState != SeqState::IDLE) {
        Serial.println(F("[seq] already running"));
        return;
    }
    if (!seqAutoMode) {
        Serial.println(F("[seq] auto mode OFF — type 'a' to arm"));
        return;
    }
    if (!seqAtHome()) {
        Serial.println(F("[seq] not at home — type 'h' first"));
        return;
    }
    activeSeq    = PICKUP_SEQUENCE;
    activeSeqLen = PICKUP_SEQUENCE_LEN;
    seqIndex     = 0;
    seqState     = SeqState::MOVING;
    seqEnteredMs = millis();
    seqApplyKeyframe(seqIndex);
    Serial.print(F("[seq] start ("));
    Serial.print(activeSeqLen);
    Serial.println(F(" keyframes)"));
}

// Start the grasp+drop sequence from the CURRENT pose (the servoed hover) —
// the Pi calls this once pickup_runner has aligned the claw over the rock.
// Unlike seqStart() there is NO at-home gate (we deliberately start mid-air),
// and the pickup-phase keyframes carry base == BASE_KEEP so the servoed base
// is preserved. Auto-mode only; refuses if a sequence or staged home is busy.
static void seqStartGrasp() {
    if (seqState != SeqState::IDLE) {
        Serial.println(F("[seq] already running"));
        return;
    }
    if (!seqAutoMode) {
        Serial.println(F("[seq] auto mode OFF — type 'a' to arm"));
        return;
    }
    if (homeState != HomeState::IDLE) {
        Serial.println(F("[seq] busy (home)"));
        return;
    }
    activeSeq    = GRASP_DROP_SEQUENCE;
    activeSeqLen = GRASP_DROP_SEQUENCE_LEN;
    seqIndex     = 0;
    seqState     = SeqState::MOVING;
    seqEnteredMs = millis();
    seqApplyKeyframe(seqIndex);
    Serial.print(F("[seq] grasp+drop start ("));
    Serial.print(activeSeqLen);
    Serial.println(F(" keyframes)"));
}

static void seqTick() {
    if (seqState == SeqState::IDLE) return;
    uint32_t now = millis();

    if (seqState == SeqState::MOVING) {
        seqApplyKeyframe(seqIndex);   // keep target fresh + watchdog fed
        if (seqAtTarget()) {
            seqState     = SeqState::DWELLING;
            seqEnteredMs = now;
            Serial.print(F("[seq] arrived @ kf "));
            Serial.println(seqIndex);
        }
        return;
    }

    // DWELLING — hold the pose, then advance.
    seqApplyKeyframe(seqIndex);
    if (now - seqEnteredMs < SEQ_DWELL_MS) return;

    seqIndex++;
    if (seqIndex >= activeSeqLen) {
        seqState = SeqState::IDLE;
        Serial.println(F("[seq] done"));
        return;
    }
    seqState     = SeqState::MOVING;
    seqEnteredMs = now;
    seqApplyKeyframe(seqIndex);
}

// Begin a home. If the shoulder is already up out of the stall zone there's
// nothing to sequence — snap every joint straight to KF_HOME. If it's down
// in the zone, kick off the staged fold/lift/place instead. Either way the
// claw heads home immediately, and any running pickup sequence is aborted.
static void startHome() {
    seqAbort(F("home command"));
    axes[3].target = KF_HOME.claw;                          // claw always homes
    const uint8_t shoulderNow = (uint8_t)(axes[1].current + 0.5f);
    if (shoulderNow <= SHOULDER_LIFT_GATE_DEG) {
        homeState = HomeState::IDLE;
        axes[0].target = KF_HOME.base;
        axes[1].target = KF_HOME.shoulder;
        axes[2].target = KF_HOME.elbow;
        Serial.println(F("[home] snap"));
    } else {
        homeState = HomeState::FOLD;                         // fold elbow first
        axes[0].target = KF_HOME.base;                       // base may travel freely
        axes[2].target = HOME_FOLD_ELBOW_DEG;
        Serial.println(F("[home] staged: folding elbow"));
    }
    lastFrameMs = millis();
}

// Advance the staged home. No-op when IDLE. While active it OWNS the targets
// (incoming controller frames are ignored — see applyFrame) and pets the
// link watchdog so a quiet link can't freeze it mid-home.
static void homeTick() {
    if (homeState == HomeState::IDLE) return;
    const uint8_t shoulderNow = (uint8_t)(axes[1].current + 0.5f);
    const uint8_t elbowNow    = (uint8_t)(axes[2].current + 0.5f);

    axes[0].target = KF_HOME.base;     // keep base + claw homing through every phase
    axes[3].target = KF_HOME.claw;
    lastFrameMs = millis();

    switch (homeState) {
        case HomeState::FOLD:
            axes[2].target = HOME_FOLD_ELBOW_DEG;
            if (elbowNow >= ELBOW_LIFT_SAFE_DEG) {
                homeState = HomeState::LIFT;
                Serial.println(F("[home] elbow folded — lifting shoulder"));
            }
            break;
        case HomeState::LIFT:
            axes[2].target = HOME_FOLD_ELBOW_DEG;          // stay tucked through the lift
            axes[1].target = KF_HOME.shoulder;             // interlock allows it (elbow tucked)
            if (shoulderNow <= (uint8_t)(KF_HOME.shoulder + SEQ_TOLERANCE_DEG)) {
                homeState = HomeState::PLACE;
                Serial.println(F("[home] shoulder up — placing elbow"));
            }
            break;
        case HomeState::PLACE:
            axes[1].target = KF_HOME.shoulder;
            axes[2].target = KF_HOME.elbow;                // out of the zone now — safe to extend
            if (elbowNow <= (uint8_t)(KF_HOME.elbow + SEQ_TOLERANCE_DEG)) {
                homeState = HomeState::IDLE;
                Serial.println(F("[home] done"));
            }
            break;
        default:
            break;
    }
}

// ---- E-stop --------------------------------------------------------------
// Damped (soft) e-stop: rather than cutting servo power (which would let the
// arm go limp and drop its load), we freeze every joint at its current angle
// and open the claw. The servos stay powered and HOLD position. Because every
// motion path on this board flows through the targets[] that loop() slews to,
// pinning the targets here stops manual AND autonomous motion in one place.

// Latch the stop: cancel any autonomous motion, drop out of auto so it can't
// resume on its own when the rocker is released, hold the current pose, and
// command the claw fully open. holdEstop() then keeps re-asserting this.
static void onEstopEngage() {
    seqAbort(F("E-STOP"));                // cancel a running pickup/grasp
    homeState   = HomeState::IDLE;        // cancel a staged home
    seqAutoMode = false;                  // no auto-resume after release — operator re-arms
    for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);  // hold where we are
    axes[3].target = LIM_CLAW.lo;         // open the claw all the way
    Serial.println(F("[estop] ENGAGED — holding pose, claw opening, auto OFF"));
}

static void onEstopClear() {
    // Hold position on release; control resumes normally on the next input
    // (manual frame, or the operator re-arming auto). Pet the watchdog so a
    // quiet link doesn't immediately re-freeze in a confusing way.
    for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);
    lastFrameMs = millis();
    Serial.println(F("[estop] cleared — manual control resumed (auto OFF)"));
}

// Re-assert the held pose + open claw every tick while engaged, so nothing
// (a late BT frame, a stray target write) can sneak the arm into motion.
static void holdEstop() {
    for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);
    axes[3].target = LIM_CLAW.lo;         // keep the claw opening / held open
}

// Read the rocker (debounced) and fire the engage/clear edges. Engaging is
// instant; clearing requires the RUN level to be stable for the debounce
// window so contact bounce can't flicker the arm back to life.
static void updateEstop() {
    const bool stopLevel = (digitalRead(ESTOP_PIN) == ESTOP_ENGAGED_LEVEL);
    if (stopLevel) {
        estopRunSinceMs = millis();       // reset the "stable RUN" timer
        if (!estopEngaged) { estopEngaged = true; onEstopEngage(); }
    } else if (estopEngaged &&
               (millis() - estopRunSinceMs) >= ESTOP_CLEAR_DEBOUNCE_MS) {
        estopEngaged = false;
        onEstopClear();
    }
}

// Called every time a fresh, checksum-valid frame arrives. We only update
// the *targets* — the actual servo motion is paced by slewAndWrite().
// Each angle is clamped on the way in so a buggy controller can't drive
// the arm past its mechanical stops.
//
// Manual override: a sequence is aborted only when the user is *actually*
// driving the joystick, i.e. the new frame differs from the previous one
// by more than SEQ_OVERRIDE_DEG on any axis. A parked controller sends
// identical 50 Hz heartbeats; without this check those heartbeats would
// kill the sequence ~20 ms after seqStart().
static void applyFrame(const ArmProto::Frame& f) {
    // Initialise prev to the safe starting pose so the very first frame
    // after boot (controller normally sitting at HOME too) doesn't look
    // like a giant deflection vs zero-initialised state.
    static ArmProto::Frame prev {
        LIM_BASE.initial, LIM_SHOULDER.initial,
        LIM_ELBOW.initial, LIM_CLAW.initial, 0
    };

    uint8_t maxDelta = 0;
    auto check = [&](uint8_t a, uint8_t b) {
        uint8_t d = a > b ? a - b : b - a;
        if (d > maxDelta) maxDelta = d;
    };
    // Claw is deliberately EXCLUDED from the takeover check: it's pot-driven
    // and the pot is electrically noisy (jitters ±3), so counting it would
    // keep reading "driving" and lock the arm out of auto mode. The claw is
    // Pi-controlled during the auto pickup anyway, and you take manual control
    // by moving a stick/base (still detected below) — not by nudging the claw.
    check(f.base,     prev.base);
    check(f.shoulder, prev.shoulder);
    check(f.elbow,    prev.elbow);
    prev = f;

    // Angle delta catches stick deflection + sustained button presses
    // (which integrate into base angle). FLAG_BUTTON catches the edge
    // cases: a button tap so brief it didn't yet advance the base by a
    // full degree, or pot activity that hasn't moved the rounded claw
    // value yet. Either is enough to count as "user touched something".
    // FLAG_BUTTON is deliberately NOT part of "driving". The controller sets
    // it whenever the claw pot reads "active", and a NOISY pot keeps it
    // asserted every frame even when untouched — which would peg userIsDriving
    // and lock the arm out of auto mode (observed: claw jitter ±3, BTN=1 on
    // every frame, base/shoulder/elbow dead-stable). Genuine input still
    // registers via maxDelta — a held base button spins the base, a real claw
    // turn moves the claw angle — and the streak debounce below filters the
    // isolated single-frame pot-jitter spikes. (Proper cure is controller-side:
    // raise POT_NOISE / smooth the pot so it stops reading active from noise.)
    bool userIsDriving = (maxDelta > SEQ_OVERRIDE_DEG);

    // RX debug capture (temporary).
    g_lastRx = f;
    g_lastMaxDelta = maxDelta;
    g_rxCount++;
    if (userIsDriving) g_drvCount++;

    // Debounce "driving" into a SUSTAINED manual takeover. With
    // SEQ_OVERRIDE_DEG = 0 a single degree of BT jitter reads as driving; if
    // that transient noise were allowed to act, it would knock auto mode off
    // the instant the Pi enables it and let the controller frame stomp the
    // Pi's home/hover target — so nothing moves in auto. drivingStreak counts
    // consecutive driving frames and resets on the first still frame; only a
    // streak of MANUAL_OVERRIDE_FRAMES is a genuine takeover. A real stick
    // push lasts many frames; jitter is 1-2, so it's filtered out.
    static uint8_t drivingStreak = 0;
    if (userIsDriving) {
        if (drivingStreak < 255) drivingStreak++;
    } else {
        drivingStreak = 0;
    }
    const bool manualTakeover = drivingStreak >= MANUAL_OVERRIDE_FRAMES;

    // On a genuine takeover, stamp the move time + hand control back: kick
    // auto mode OFF so the operator's joystick drives again.
    if (manualTakeover) {
        lastControllerMoveMs = millis();
        if (seqAutoMode) {
            seqAutoMode = false;
            Serial.println(F("[seq] auto OFF (controller moved)"));
        }
    }

    // Staged home request (FLAG_HOME). Edge-triggered so we launch once per
    // request rather than restarting every frame in the hold window.
    const bool homeFlag = (f.flags & ArmProto::FLAG_HOME) != 0;
    static bool prevHomeFlag = false;
    if (homeFlag && !prevHomeFlag) startHome();
    prevHomeFlag = homeFlag;

    if (homeState != HomeState::IDLE) {
        // homeTick() owns the targets while a home runs. Only a SUSTAINED
        // joystick move (not a jitter blip) once FLAG_HOME has cleared
        // cancels it — otherwise BT noise would abort the auto-home.
        if (!homeFlag && manualTakeover) {
            homeState = HomeState::IDLE;
            for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);
            Serial.println(F("[home] cancelled (joystick)"));
        }
        lastFrameMs = millis();
        return;
    }

    if ((seqState != SeqState::IDLE || seqAutoMode) && !manualTakeover) {
        // Heartbeat OR transient jitter from the controller while a sequence
        // runs or auto mode is armed: ignore it (seqTick / the Pi own the
        // targets), just pet the BT-link watchdog so it doesn't freeze us.
        // Only a sustained manual takeover falls through to hand control back.
        lastFrameMs = millis();
        return;
    }

    if (seqState != SeqState::IDLE) {
        seqAbort(F("manual override (joystick)"));
    }
    axes[0].target = clampTo(f.base,     axes[0].lim);
    axes[1].target = clampTo(f.shoulder, axes[1].lim);
    axes[2].target = clampTo(f.elbow,    axes[2].lim);
    axes[3].target = clampTo(f.claw,     axes[3].lim);
    lastFrameMs = millis();   // pet the watchdog — we just heard from the controller
}

// Step every joint one tick closer to its target, never moving more than
// MAX_DEG_PER_SEC * dt degrees in a single tick. This is the "slew rate
// limit" that turns a step input from the controller into a smooth ramp.
//
// dtMs = how long it's actually been since the last tick (usually ~20 ms,
// but using the real value keeps motion uniform if a tick gets delayed).
// Shoulder lift interlock. Run once per tick AFTER targets are set (from a
// BT frame, keyframe, or watchdog) and BEFORE slewAndWrite(), so it gets
// the last word on the shoulder target. If the shoulder is down in the
// stall zone and the elbow is NOT yet tucked back far enough, we clamp the
// shoulder target so it can't rise (target may not drop below where the
// shoulder currently is) — i.e. we pause the shoulder's upward motion.
// Lowering the shoulder and moving the elbow are untouched. As soon as the
// elbow is tucked past ELBOW_LIFT_SAFE_DEG the clamp lifts and the queued
// upward command goes through. See SHOULDER_LIFT_GATE_DEG / interlock notes.
static void applyShoulderLiftGate() {
    const uint8_t shoulderNow = (uint8_t)(axes[1].current + 0.5f);  // where the shoulder actually is
    const uint8_t elbowNow    = (uint8_t)(axes[2].current + 0.5f);  // where the elbow actually is
    const bool inStallZone = shoulderNow >  SHOULDER_LIFT_GATE_DEG;
    const bool elbowTucked = elbowNow    >= ELBOW_LIFT_SAFE_DEG;
    if (inStallZone && !elbowTucked && axes[1].target < shoulderNow) {
        axes[1].target = shoulderNow;   // veto the lift — hold until the elbow is bent back
    }
}

static void slewAndWrite(uint32_t dtMs) {
    const float stepMax = MAX_DEG_PER_SEC * (dtMs / 1000.0f);  // max degrees we may move this tick
    for (auto& a : axes) {                                     // `auto&` = "reference to whatever's in axes[]"
        float err = (float)a.target - a.current;               // how far we still want to go
        if (err >  stepMax) err =  stepMax;                    // cap forward speed
        if (err < -stepMax) err = -stepMax;                    // cap reverse speed
        a.current += err;                                      // advance our internal angle
        // Final defence-in-depth clamp. `target` is already clamped on
        // input and `current` is bounded by integration toward target,
        // so this never trips today — but if either invariant ever
        // breaks (e.g. someone writes a.current from a sort-mode planner
        // without re-clamping), the servo still gets a value inside the
        // mechanical envelope.
        uint8_t out = (uint8_t)(a.current + 0.5f);
        out = clampTo(out, a.lim);
        a.servo.write(out);
    }
}

// Print current servo angles once per second. Visible in `pio device monitor`.
static void logPositions() {
    uint32_t now = millis();
    if (now - lastPosLogMs < 1000) return;
    lastPosLogMs = now;
    Serial.print(F("[pos] base="));    Serial.print((int)(axes[0].current + 0.5f));
    Serial.print(F(" shoulder="));     Serial.print((int)(axes[1].current + 0.5f));
    Serial.print(F(" elbow="));        Serial.print((int)(axes[2].current + 0.5f));
    Serial.print(F(" claw="));         Serial.println((int)(axes[3].current + 0.5f));
}

// ---------------------------------------------------------------------
// USB serial command surface. One newline-terminated line per command,
// mirroring the controller's `pumpSerialCommands()` parser so both
// firmwares speak the same way (and so `b<deg>` can carry a multi-digit
// argument that a bare-char reader couldn't).
//
//   p          pickup sequence            x   abort
//   h          staged home                a   toggle auto mode
//   ?          status dump
//   v          hover: lift to the approach pose, leaving base untouched
//   b<deg>     set base angle absolutely  (Pi visual-servo nudge)
//   g          grasp+drop from the current (servoed hover) pose
//
// 'v' and 'b<deg>' are the visual-servo primitives: the Pi sends 'v' to
// raise the arm into the hover pose over the pickup zone, then streams
// 'b<deg>' to swing the base until the claw is on the rock's bearing,
// then 'p' to grasp. Both are auto-mode-only and refuse while a sequence
// or staged home owns the joints — so they can't fight those motions.
static char    usbBuf[16];
static uint8_t usbLen = 0;

static void handleUsbCommand(char* line) {
    while (*line == ' ' || *line == '\t') ++line;       // strip leading space
    if (*line == '\0') return;                          // blank line — ignore
    char cmd = *line++;
    if (cmd >= 'A' && cmd <= 'Z') cmd = (char)(cmd + 32);   // tolower

    // While e-stopped, refuse everything that moves the arm. Status ('?') and
    // the rx-debug toggle ('d') are read-only, so they're still allowed.
    if (estopEngaged && cmd != '?' && cmd != 'd') {
        Serial.println(F("[estop] engaged — command ignored"));
        return;
    }

    switch (cmd) {
        case 'p':
            seqStart();
            break;
        case 'g':
            // Grasp+drop from the current servoed hover (the Pi's ALIGNED
            // state). seqStartGrasp() enforces auto-mode + not-busy itself.
            seqStartGrasp();
            break;
        case 'x':
            seqAbort(F("user 'x'"));
            break;
        case 'a':
            // Turning auto OFF is always safe. Turning it ON requires the
            // controller to have been parked for CONTROLLER_IDLE_MS — stops
            // you arming the arm while a stick is still deflected, which the
            // next BT frame would otherwise read as "driving" and flip auto
            // straight back off.
            if (!seqAutoMode && !controllerIdle()) {
                Serial.println(F("[seq] cannot arm — controller still moving"));
                break;
            }
            seqAutoMode = !seqAutoMode;
            Serial.print(F("[seq] auto mode "));
            Serial.println(seqAutoMode ? F("ON") : F("OFF"));
            // Entering auto homes the arm (claw included) so it always starts
            // from a known pose — you no longer have to home it by hand first.
            // Staged when the shoulder is down, a straight snap otherwise.
            if (seqAutoMode) startHome();
            break;
        case 'h':
            // Staged when the shoulder is down, straight snap otherwise.
            startHome();
            break;
        case 'v':
            // Hover pose: shoulder/elbow/claw to the jogged HOVER pose, base
            // deliberately left where it is so the Pi can aim it next.
            if (!seqAutoMode) {
                Serial.println(F("[hover] auto OFF — type 'a' first"));
                break;
            }
            if (seqState != SeqState::IDLE || homeState != HomeState::IDLE) {
                Serial.println(F("[hover] busy"));
                break;
            }
            axes[1].target = clampTo(HOVER.shoulder, axes[1].lim);
            axes[2].target = clampTo(HOVER.elbow,    axes[2].lim);
            axes[3].target = clampTo(HOVER.claw,     axes[3].lim);
            lastFrameMs = millis();            // pet the watchdog — Pi is driving
            Serial.println(F("[hover] pose"));
            break;
        case 'b': {
            // Absolute base angle from the Pi visual-servo loop. atoi reads
            // the integer after the 'b'; constrain before the uint8_t cast so
            // a stray negative can't wrap up to a huge angle.
            if (!seqAutoMode) {
                Serial.println(F("[base] auto OFF — type 'a' first"));
                break;
            }
            if (seqState != SeqState::IDLE || homeState != HomeState::IDLE) {
                Serial.println(F("[base] busy"));
                break;
            }
            int deg = constrain(atoi(line), 0, 180);
            axes[0].target = clampTo((uint8_t)deg, axes[0].lim);
            lastFrameMs = millis();            // pet the watchdog — Pi is driving
            Serial.print(F("[base] target="));
            Serial.println(axes[0].target);
            break;
        }
        case 'd':
            g_rxDebug = !g_rxDebug;
            Serial.print(F("[rx] debug "));
            Serial.println(g_rxDebug ? F("ON") : F("OFF"));
            break;
        case '?':
            Serial.print(F("[seq] auto="));
            Serial.print(seqAutoMode ? F("ON") : F("OFF"));
            Serial.print(F(" state="));
            Serial.print((uint8_t)seqState);
            Serial.print(F(" idx="));
            Serial.print(seqIndex);
            Serial.print(F(" atHome="));
            Serial.print(seqAtHome() ? F("yes") : F("no"));
            Serial.print(F(" estop="));
            Serial.println(estopEngaged ? F("yes") : F("no"));
            break;
        default:
            break;   // unknown command — ignore
    }
}

// ---------------------------------------------------------------------
// Arduino calls setup() once at power-on / after reset.
void setup() {
    Serial.begin(115200);          // USB — debug log (visible in `pio device monitor`)
    Serial1.begin(9600);           // Hardware UART on D18/D19 — talks to the HC-05.
                                   // 9600 must match what we set with AT+UART
                                   // when configuring the modules.

    // Tell the Servo library which pin to drive for each joint. `.attach()`
    // hooks the pin into the library's internal 50 Hz pulse generator.
    servoBase.attach(SERVO_PIN_BASE);
    servoShoulder.attach(SERVO_PIN_SHOULDER);
    servoElbow.attach(SERVO_PIN_ELBOW);
    servoClaw.attach(SERVO_PIN_CLAW);

    // Move to the safe starting pose immediately so the arm doesn't sit
    // at whatever random angle the servos last held.
    for (auto& a : axes) a.servo.write(a.lim.initial);

    // E-stop rocker, read with the internal pull-up (see ESTOP_PIN notes).
    // Seed the debounce timer + latch the initial state so we boot stopped if
    // the rocker is already in the E-STOP position.
    pinMode(ESTOP_PIN, INPUT_PULLUP);
    estopRunSinceMs = millis();
    updateEstop();

    // F("...") stores the string in flash (program memory) instead of RAM.
    // RAM is precious on the Mega (8 KB) — every F() saves a few bytes.
    Serial.println(F("[arm] boot OK — Serial1=HC-05@9600"));
    lastFrameMs = millis();
    lastTickMs  = millis();
}

// Arduino calls loop() over and over, as fast as it can, forever.
void loop() {
    // 0. Poll the e-stop rocker first, so the rest of the loop sees a fresh
    //    estopEngaged. When engaged it overrides everything below.
    updateEstop();

    // 1. Drain the Bluetooth receive buffer. `Serial1.available()` returns
    //    how many unread bytes are sat in the UART's hardware FIFO. We
    //    feed each one to the decoder; it returns true when it has a
    //    complete, checksum-valid 7-byte frame. While e-stopped we still drain
    //    the FIFO (so it can't overflow) but ignore the frames.
    while (Serial1.available()) {
        ArmProto::Frame f;
        if (decoder.feed((uint8_t)Serial1.read(), f) && !estopEngaged) {
            applyFrame(f);
        }
    }

    logPositions();

    // Pose report back to the controller (bumpless handoff). At ~15 Hz, send
    // our actual current pose over the HC-05 with FLAG_AUTO set whenever the
    // arm is driving itself, so the controller can track us and a switch back
    // to manual doesn't jump. The HC-05 SPP link is full-duplex, so this
    // shares the wire with the controller's command stream fine.
    static uint32_t lastPoseTxMs = 0;
    if (millis() - lastPoseTxMs >= 66) {
        lastPoseTxMs = millis();
        ArmProto::Frame pf;
        pf.base     = (uint8_t)(axes[0].current + 0.5f);
        pf.shoulder = (uint8_t)(axes[1].current + 0.5f);
        pf.elbow    = (uint8_t)(axes[2].current + 0.5f);
        pf.claw     = (uint8_t)(axes[3].current + 0.5f);
        // Mark the pose "autonomous" while e-stopped too, so the controller
        // tracks the held pose and resumes bumplessly when the rocker clears.
        const bool autonomous = seqAutoMode
                             || homeState != HomeState::IDLE
                             || seqState  != SeqState::IDLE
                             || estopEngaged;
        pf.flags = autonomous ? ArmProto::FLAG_AUTO : 0;
        uint8_t pbuf[ArmProto::FRAME_SIZE];
        ArmProto::encode(pf, pbuf);
        Serial1.write(pbuf, ArmProto::FRAME_SIZE);
    }

    // RX debug dump (temporary) — n=frames this interval, drv=how many read as
    // "driving", then the last frame's angles + decoded flags. n=0 means no BT
    // frames arrived (controller off / unpaired).
    if (g_rxDebug && millis() - g_lastRxDbgMs >= 500) {
        g_lastRxDbgMs = millis();
        Serial.print(F("[rx] n="));     Serial.print(g_rxCount);
        Serial.print(F(" drv="));       Serial.print(g_drvCount);
        Serial.print(F(" b="));         Serial.print(g_lastRx.base);
        Serial.print(F(" s="));         Serial.print(g_lastRx.shoulder);
        Serial.print(F(" e="));         Serial.print(g_lastRx.elbow);
        Serial.print(F(" c="));         Serial.print(g_lastRx.claw);
        Serial.print(F(" flags="));     Serial.print(g_lastRx.flags);
        Serial.print(F(" BTN="));       Serial.print((g_lastRx.flags & ArmProto::FLAG_BUTTON) ? 1 : 0);
        Serial.print(F(" HOME="));      Serial.print((g_lastRx.flags & ArmProto::FLAG_HOME) ? 1 : 0);
        Serial.print(F(" maxd="));      Serial.println(g_lastMaxDelta);
        g_rxCount = 0; g_drvCount = 0;
    }

    // 1c. USB serial commands. One newline-terminated line each (a bare
    //     "p\n", or "b120\n" with an argument) — see handleUsbCommand().
    //     Accumulate bytes into usbBuf until CR/LF, then dispatch. Lines
    //     longer than the buffer are dropped and resync at the next newline.
    while (Serial.available()) {
        int ci = Serial.read();
        if (ci < 0) break;
        char c = (char)ci;
        if (c == '\r' || c == '\n') {
            if (usbLen > 0) {
                usbBuf[usbLen] = '\0';
                handleUsbCommand(usbBuf);
                usbLen = 0;
            }
        } else if (usbLen < sizeof(usbBuf) - 1) {
            usbBuf[usbLen++] = c;
        } else {
            usbLen = 0;     // overflow — drop and resync at next newline
        }
    }

    // 1d. Advance the pickup sequence + staged home. Both no-op when IDLE.
    //     Frozen while e-stopped — holdEstop() owns the targets instead.
    if (!estopEngaged) {
        seqTick();
        homeTick();
    }

    // 2. Every TICK_MS, slew the servos one step toward their targets.
    uint32_t now = millis();
    if (now - lastTickMs >= TICK_MS) {
        uint32_t dt = now - lastTickMs;   // actual elapsed time, used by slewAndWrite
        lastTickMs = now;

        // Link watchdog: if we haven't heard a valid frame for too long,
        // pretend the target is wherever we currently are. The slew step
        // then has zero error, so the arm stops mid-motion instead of
        // sailing on toward the last received target.
        //
        // Suppressed in auto mode: there the Pi (over USB) is the command
        // authority, not the BT link, and a Pi-set target ('v'/'b'/keyframe)
        // can take longer than LINK_TIMEOUT_MS to slew to. We must not freeze
        // it just because the controller is parked or powered off. There's no
        // runaway risk — in auto mode the BT frames aren't driving the arm.
        if (!seqAutoMode && now - lastFrameMs > LINK_TIMEOUT_MS) {
            for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);
        }

        // E-stop has the final say on the targets: pin every joint to its
        // current angle (hold) and keep the claw opening. Runs after the
        // watchdog so nothing else can move the arm while engaged.
        if (estopEngaged) holdEstop();

        // Veto shoulder lifts while it's down and the elbow isn't tucked.
        // Runs after the watchdog so a dropped link can't sneak a lift past.
        applyShoulderLiftGate();

        slewAndWrite(dt);
    }
    // Note: nothing else runs in loop(), so this is a tight poll. If you
    // ever add work here, keep it short — anything > a few ms eats into
    // the tick budget and motion gets jerky.
}
