// arm_mega/main.cpp
// ----------------------------------------------------------------------
// Runs on the Elegoo Mega 2560 R3 mounted on the arm base.
//
// Responsibilities:
//   1. Receive 7-byte framed packets from the HC-05 (paired as SLAVE)
//      on Serial1 at 9600 baud.
//   2. Rate-limit commanded angles into smooth servo motion (slew).
//   3. Fail-safe: if no valid frame for LINK_TIMEOUT_MS, freeze in place.
//
// Vision lives on the Raspberry Pi side now (Logitech C270 + OpenCV in
// vision/colour_detect.py). The Mega has no on-board camera link.
//
// Wiring (Mega):
//   HC-05  VCC  -> 5V
//   HC-05  GND  -> GND
//   HC-05  TXD  -> Mega D19  (RX1)           [HC-05 TX is 3.3V-ish, Mega accepts]
//   HC-05  RXD  -> Mega D18  (TX1) via divider (see wiring guide)
//   Servos     : see SERVO_PIN_* below. Power from external 4xAA pack,
//                NOT from the Mega's 5V rail. Share GND with the Mega.
//
// IMPORTANT — pin choice on Mega:
//   The Servo library on Mega supports servos on ANY digital pin (unlike
//   the Uno). D9/10/11 are fine; D6 is used for the claw to keep lines
//   away from the SPI header in case we add sensors later.
// ----------------------------------------------------------------------

#include <Arduino.h>      // Core Arduino types/functions (millis(), Serial, etc.)
#include <Servo.h>        // Standard Arduino Servo library — generates the PWM
                          // pulse train that an MG996R expects (1.0..2.0 ms
                          // pulse every ~20 ms, mapped to 0..180 degrees).
#include <ArmProtocol.h>  // Our shared header in lib/ArmProtocol — defines the
                          // 7-byte packet format and the byte-by-byte decoder.
#include "keyframes.h"    // Pickup-sequence poses. Generated by
                          // scripts/record_keyframes.py — placeholder
                          // (all-HOME) is checked in so the build works
                          // before you've recorded.

// ---- Pin assignments ------------------------------------------------
// Which Mega digital pin each servo's signal wire is connected to. Change
// these here ONLY if you re-route the wiring; the rest of the code reads
// these constants instead of hard-coded numbers, so you don't have to hunt
// through the file. (`static constexpr uint8_t` = compile-time constant,
// 1 byte, file-local — the C++ way to say "#define a small integer".)
static constexpr uint8_t SERVO_PIN_BASE     = 9;
static constexpr uint8_t SERVO_PIN_SHOULDER = 7;
static constexpr uint8_t SERVO_PIN_ELBOW    = 11;
static constexpr uint8_t SERVO_PIN_CLAW     = 6;

// ---- Motion limits --------------------------------------------------
// Tune these AFTER mechanical bring-up — set the lower/upper so the arm
// cannot drive itself into its own frame. Start conservative.
//
// `Limits` bundles three numbers per joint:
//   lo      = lowest angle (degrees) we will ever command
//   hi      = highest angle we will ever command
//   initial = where the joint should sit at power-on (the "safe pose")
// Keeping them grouped means we can pass one struct around instead of
// three loose variables, and the compiler can inline the whole thing.
struct Limits { uint8_t lo, hi, initial; };
static constexpr Limits LIM_BASE     {  0, 180, 142 };
static constexpr Limits LIM_SHOULDER { 30, 140,  30 };
static constexpr Limits LIM_ELBOW    { 30, 150, 113 };
static constexpr Limits LIM_CLAW     { 20, 160,  21 };

// Max angular speed per servo. 60 deg/s is well below MG996R stall current
// even at the shoulder's worst-case lever arm (arm fully extended), which
// reduces the chance of the motor losing sync with its commanded angle —
// the open-loop failure mode that triggered this slowdown. Same value for
// every joint so the arm behaves uniformly and is easier to drive/debug.
// This is what makes the arm move SMOOTHLY instead of snapping instantly
// to whatever angle the joystick last asked for — see slewAndWrite().
static constexpr float MAX_DEG_PER_SEC = 60.0f;

// If we haven't seen a valid frame in this long, hold position.
// Acts as a safety net: if the BT link drops or the controller is
// switched off mid-motion, the arm freezes instead of running away.
static constexpr uint32_t LINK_TIMEOUT_MS = 500;

// Update tick — how often we re-compute slewed angles and write servos.
// 20 ms = 50 Hz. The Servo library refreshes pulses at ~50 Hz internally
// anyway, so going faster here would just waste CPU.
static constexpr uint32_t TICK_MS = 20;  // 50 Hz

// ---- Pickup-sequence tunables --------------------------------------
// How close each joint must be to a keyframe before we count as "arrived".
// 2° is well within MG996R repeatability and above one slew step
// (60°/s * 20 ms = 1.2°/tick) so we don't oscillate around the target.
static constexpr uint8_t  SEQ_TOLERANCE_DEG = 2;
// Hold each pose this long after arrival. Critical at GRASP_CLOSE /
// DROP_RELEASE — gives the gripper time to actually close/open before
// we slew off to the next keyframe.
static constexpr uint32_t SEQ_DWELL_MS      = 250;
// Tolerance for the "is the arm at home?" gate. Looser than the keyframe
// tolerance because manual homing is open-loop and the user might be a
// degree or two off after pressing 'h' on the controller.
static constexpr uint8_t  SEQ_HOME_TOL_DEG  = 5;
// Any axis moving by more than this between consecutive BT frames is
// treated as the user actively driving the joystick. Set to 0 so even a
// single degree of intentional input on the controller kicks the arm
// out of auto mode — the user wanted "any movement on the remote
// overrides auto". userIsDriving also OR's in the FLAG_BUTTON bit from
// the protocol to catch base-button taps and pot activity that may not
// register as an angle change between two consecutive frames.
// Safe because a truly parked controller emits identical frames (the
// joystick deadzone + pot arming gate suppress all numerical drift on
// the controller side, so maxDelta is genuinely 0 when nobody's
// touching it).
static constexpr uint8_t  SEQ_OVERRIDE_DEG  = 0;
// The controller is considered "idle" (no joystick movement) once this
// much time has passed since the last frame whose delta exceeded
// SEQ_OVERRIDE_DEG. Used to gate entry into auto mode — we refuse 'a' to
// turn auto ON unless the controller has been parked for this long, so
// you can't arm the arm while you're mid-stick-push.
static constexpr uint32_t CONTROLLER_IDLE_MS = 500;

// ---- State ----------------------------------------------------------
// Four Servo objects, one per joint. `Servo` is a class from <Servo.h>;
// declaring an object here reserves a slot in the library's internal
// table of active servos. We don't .attach() them until setup().
Servo servoBase, servoShoulder, servoElbow, servoClaw;

// One decoder instance that "owns" the 7-byte buffer for in-progress
// frames coming in from Serial1. Stateful: it remembers how many bytes
// of the next frame it has already seen.
ArmProto::Decoder decoder;

// One row per joint. Bundling per-axis info into a struct lets the rest
// of the code loop over `axes[]` instead of repeating the same logic
// four times. References (`Limits&`, `Servo&`) mean the struct points
// at the original objects — no copies, no risk of writing to a copy.
struct AxisState {
    float current;       // what we're actually commanding right now (slewed,
                         // float so we can move by fractional degrees per tick)
    uint8_t target;      // the latest angle the controller asked for
    const Limits& lim;   // motion limits for this joint (read-only)
    Servo& servo;        // the Servo object we write the pulse to
};

// Initialise each axis: start at the safe pose, target the safe pose
// (so we don't immediately move on boot), and bind the lim/servo refs.
AxisState axes[] = {
    { (float)LIM_BASE.initial,     LIM_BASE.initial,     LIM_BASE,     servoBase     },
    { (float)LIM_SHOULDER.initial, LIM_SHOULDER.initial, LIM_SHOULDER, servoShoulder },
    { (float)LIM_ELBOW.initial,    LIM_ELBOW.initial,    LIM_ELBOW,    servoElbow    },
    { (float)LIM_CLAW.initial,     LIM_CLAW.initial,     LIM_CLAW,     servoClaw     },
};

// Timestamps (milliseconds since boot, from millis()).
uint32_t lastFrameMs  = 0;   // when we last received a valid frame — fed the watchdog
uint32_t lastTickMs   = 0;   // when we last ran the slew/write step
uint32_t lastPosLogMs = 0;   // when we last printed servo positions

// ---------------------------------------------------------------------
// Squash a value into the [lo, hi] range. `inline` hints the compiler to
// paste the body at each call site (cheap, the function is tiny).
static inline uint8_t clampTo(uint8_t v, const Limits& l) {
    if (v < l.lo) return l.lo;
    if (v > l.hi) return l.hi;
    return v;
}

// ---------------------------------------------------------------------
// Pickup-sequence runner state + helpers.
// IDLE: nothing happening, manual control as normal.
// MOVING: slewing toward PICKUP_SEQUENCE[seqIndex].
// DWELLING: arrived at that keyframe, holding for SEQ_DWELL_MS before
//           advancing to the next one.
// ---------------------------------------------------------------------
enum class SeqState : uint8_t { IDLE, MOVING, DWELLING };
static SeqState seqState     = SeqState::IDLE;
static uint8_t  seqIndex     = 0;            // index into PICKUP_SEQUENCE[]
static uint32_t seqEnteredMs = 0;            // millis() when current state began
static bool     seqAutoMode  = false;        // false = triggers are ignored
// millis() at the last frame whose delta exceeded SEQ_OVERRIDE_DEG.
// Updated by applyFrame() and read by controllerIdle() / the 'a' handler
// to enforce "can only enable auto mode while the controller is parked".
static uint32_t lastControllerMoveMs = 0;

// True iff the controller has been parked (no over-threshold motion) for
// CONTROLLER_IDLE_MS. Note this is also true at boot before any frame has
// arrived — that's intentional, you can arm auto mode before powering
// the controller on.
static inline bool controllerIdle() {
    return (millis() - lastControllerMoveMs) > CONTROLLER_IDLE_MS;
}

// Push PICKUP_SEQUENCE[i] into axes[].target and pet the BT watchdog so
// the link-timeout check in loop() doesn't snap targets back to current
// and freeze us mid-sequence.
static void seqApplyKeyframe(uint8_t i) {
    const Pose& kf = PICKUP_SEQUENCE[i];
    axes[0].target = clampTo(kf.base,     axes[0].lim);
    axes[1].target = clampTo(kf.shoulder, axes[1].lim);
    axes[2].target = clampTo(kf.elbow,    axes[2].lim);
    axes[3].target = clampTo(kf.claw,     axes[3].lim);
    lastFrameMs = millis();
}

// All four joints within SEQ_TOLERANCE_DEG of their current target?
static bool seqAtTarget() {
    for (auto& a : axes) {
        int err = (int)a.target - (int)(a.current + 0.5f);
        if (err < 0) err = -err;
        if (err > SEQ_TOLERANCE_DEG) return false;
    }
    return true;
}

// All four joints within SEQ_HOME_TOL_DEG of KF_HOME? Used by the
// "only auto-trigger when parked at home" safety gate.
static bool seqAtHome() {
    auto near = [](float cur, uint8_t want) {
        int err = (int)(cur + 0.5f) - (int)want;
        if (err < 0) err = -err;
        return err <= SEQ_HOME_TOL_DEG;
    };
    return near(axes[0].current, KF_HOME.base)
        && near(axes[1].current, KF_HOME.shoulder)
        && near(axes[2].current, KF_HOME.elbow)
        && near(axes[3].current, KF_HOME.claw);
}

static void seqAbort(const __FlashStringHelper* why) {
    if (seqState == SeqState::IDLE) return;
    seqState = SeqState::IDLE;
    // Freeze in place: target = current, mirroring the BT-link watchdog.
    for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);
    Serial.print(F("[seq] abort: "));
    Serial.println(why);
}

static void seqStart() {
    if (seqState != SeqState::IDLE) {
        Serial.println(F("[seq] already running"));
        return;
    }
    if (!seqAutoMode) {
        Serial.println(F("[seq] auto mode OFF — type 'a' to arm"));
        return;
    }
    if (!seqAtHome()) {
        Serial.println(F("[seq] not at home — type 'h' first"));
        return;
    }
    seqIndex     = 0;
    seqState     = SeqState::MOVING;
    seqEnteredMs = millis();
    seqApplyKeyframe(seqIndex);
    Serial.print(F("[seq] start ("));
    Serial.print(PICKUP_SEQUENCE_LEN);
    Serial.println(F(" keyframes)"));
}

static void seqTick() {
    if (seqState == SeqState::IDLE) return;
    uint32_t now = millis();

    if (seqState == SeqState::MOVING) {
        seqApplyKeyframe(seqIndex);   // keep target fresh + watchdog fed
        if (seqAtTarget()) {
            seqState     = SeqState::DWELLING;
            seqEnteredMs = now;
            Serial.print(F("[seq] arrived @ kf "));
            Serial.println(seqIndex);
        }
        return;
    }

    // DWELLING — hold the pose, then advance.
    seqApplyKeyframe(seqIndex);
    if (now - seqEnteredMs < SEQ_DWELL_MS) return;

    seqIndex++;
    if (seqIndex >= PICKUP_SEQUENCE_LEN) {
        seqState = SeqState::IDLE;
        Serial.println(F("[seq] done"));
        return;
    }
    seqState     = SeqState::MOVING;
    seqEnteredMs = now;
    seqApplyKeyframe(seqIndex);
}

// Called every time a fresh, checksum-valid frame arrives. We only update
// the *targets* — the actual servo motion is paced by slewAndWrite().
// Each angle is clamped on the way in so a buggy controller can't drive
// the arm past its mechanical stops.
//
// Manual override: a sequence is aborted only when the user is *actually*
// driving the joystick, i.e. the new frame differs from the previous one
// by more than SEQ_OVERRIDE_DEG on any axis. A parked controller sends
// identical 50 Hz heartbeats; without this check those heartbeats would
// kill the sequence ~20 ms after seqStart().
static void applyFrame(const ArmProto::Frame& f) {
    // Initialise prev to the safe starting pose so the very first frame
    // after boot (controller normally sitting at HOME too) doesn't look
    // like a giant deflection vs zero-initialised state.
    static ArmProto::Frame prev {
        LIM_BASE.initial, LIM_SHOULDER.initial,
        LIM_ELBOW.initial, LIM_CLAW.initial, 0
    };

    uint8_t maxDelta = 0;
    auto check = [&](uint8_t a, uint8_t b) {
        uint8_t d = a > b ? a - b : b - a;
        if (d > maxDelta) maxDelta = d;
    };
    check(f.base,     prev.base);
    check(f.shoulder, prev.shoulder);
    check(f.elbow,    prev.elbow);
    check(f.claw,     prev.claw);
    prev = f;

    // Angle delta catches stick deflection + sustained button presses
    // (which integrate into base angle). FLAG_BUTTON catches the edge
    // cases: a button tap so brief it didn't yet advance the base by a
    // full degree, or pot activity that hasn't moved the rounded claw
    // value yet. Either is enough to count as "user touched something".
    bool userIsDriving = (maxDelta > SEQ_OVERRIDE_DEG)
                      || (f.flags & ArmProto::FLAG_BUTTON);

    // Stamp the last-move timestamp + kick auto mode OFF the moment the
    // user touches the sticks. The 'a' command consults controllerIdle()
    // (set by the stamp below) before allowing auto to be re-enabled, so
    // you can't arm a sequence while you're still driving manually.
    if (userIsDriving) {
        lastControllerMoveMs = millis();
        if (seqAutoMode) {
            seqAutoMode = false;
            Serial.println(F("[seq] auto OFF (controller moved)"));
        }
    }

    if ((seqState != SeqState::IDLE || seqAutoMode) && !userIsDriving) {
        // Heartbeat from a parked controller. Two cases for ignoring it:
        //   - A sequence is running (seqTick owns the targets).
        //   - Auto mode is armed (Pi is in charge; the controller's
        //     unchanging command stream must not stomp Pi-set targets
        //     like 'h' or a pickup keyframe).
        // Either way, pet the BT-link watchdog so it doesn't freeze the
        // arm, but leave targets alone. As soon as a stick is moved
        // (userIsDriving = true), the block above turns auto OFF and
        // execution falls through to apply the new frame normally.
        lastFrameMs = millis();
        return;
    }

    if (seqState != SeqState::IDLE) {
        seqAbort(F("manual override (joystick)"));
    }
    axes[0].target = clampTo(f.base,     axes[0].lim);
    axes[1].target = clampTo(f.shoulder, axes[1].lim);
    axes[2].target = clampTo(f.elbow,    axes[2].lim);
    axes[3].target = clampTo(f.claw,     axes[3].lim);
    lastFrameMs = millis();   // pet the watchdog — we just heard from the controller
}

// Step every joint one tick closer to its target, never moving more than
// MAX_DEG_PER_SEC * dt degrees in a single tick. This is the "slew rate
// limit" that turns a step input from the controller into a smooth ramp.
//
// dtMs = how long it's actually been since the last tick (usually ~20 ms,
// but using the real value keeps motion uniform if a tick gets delayed).
static void slewAndWrite(uint32_t dtMs) {
    const float stepMax = MAX_DEG_PER_SEC * (dtMs / 1000.0f);  // max degrees we may move this tick
    for (auto& a : axes) {                                     // `auto&` = "reference to whatever's in axes[]"
        float err = (float)a.target - a.current;               // how far we still want to go
        if (err >  stepMax) err =  stepMax;                    // cap forward speed
        if (err < -stepMax) err = -stepMax;                    // cap reverse speed
        a.current += err;                                      // advance our internal angle
        // Final defence-in-depth clamp. `target` is already clamped on
        // input and `current` is bounded by integration toward target,
        // so this never trips today — but if either invariant ever
        // breaks (e.g. someone writes a.current from a sort-mode planner
        // without re-clamping), the servo still gets a value inside the
        // mechanical envelope.
        uint8_t out = (uint8_t)(a.current + 0.5f);
        out = clampTo(out, a.lim);
        a.servo.write(out);
    }
}

// Print current servo angles once per second. Visible in `pio device monitor`.
static void logPositions() {
    uint32_t now = millis();
    if (now - lastPosLogMs < 1000) return;
    lastPosLogMs = now;
    Serial.print(F("[pos] base="));    Serial.print((int)(axes[0].current + 0.5f));
    Serial.print(F(" shoulder="));     Serial.print((int)(axes[1].current + 0.5f));
    Serial.print(F(" elbow="));        Serial.print((int)(axes[2].current + 0.5f));
    Serial.print(F(" claw="));         Serial.println((int)(axes[3].current + 0.5f));
}

// ---------------------------------------------------------------------
// Arduino calls setup() once at power-on / after reset.
void setup() {
    Serial.begin(115200);          // USB — debug log (visible in `pio device monitor`)
    Serial1.begin(9600);           // Hardware UART on D18/D19 — talks to the HC-05.
                                   // 9600 must match what we set with AT+UART
                                   // when configuring the modules.

    // Tell the Servo library which pin to drive for each joint. `.attach()`
    // hooks the pin into the library's internal 50 Hz pulse generator.
    servoBase.attach(SERVO_PIN_BASE);
    servoShoulder.attach(SERVO_PIN_SHOULDER);
    servoElbow.attach(SERVO_PIN_ELBOW);
    servoClaw.attach(SERVO_PIN_CLAW);

    // Move to the safe starting pose immediately so the arm doesn't sit
    // at whatever random angle the servos last held.
    for (auto& a : axes) a.servo.write(a.lim.initial);

    // F("...") stores the string in flash (program memory) instead of RAM.
    // RAM is precious on the Mega (8 KB) — every F() saves a few bytes.
    Serial.println(F("[arm] boot OK — Serial1=HC-05@9600"));
    lastFrameMs = millis();
    lastTickMs  = millis();
}

// Arduino calls loop() over and over, as fast as it can, forever.
void loop() {
    // 1. Drain the Bluetooth receive buffer. `Serial1.available()` returns
    //    how many unread bytes are sat in the UART's hardware FIFO. We
    //    feed each one to the decoder; it returns true when it has a
    //    complete, checksum-valid 7-byte frame.
    while (Serial1.available()) {
        ArmProto::Frame f;
        if (decoder.feed((uint8_t)Serial1.read(), f)) {
            applyFrame(f);
        }
    }

    logPositions();

    // 1c. USB serial commands — test triggers + mode toggle. Each char
    //     is a single keystroke from `pio device monitor`. No newline
    //     required, so you can drive the sequence with bare letters.
    //       p  pickup    a  toggle auto mode    h  home
    //       x  abort     ?  status dump
    while (Serial.available()) {
        char c = (char)Serial.read();
        switch (c) {
            case 'p': case 'P':
                seqStart();
                break;
            case 'x': case 'X':
                seqAbort(F("user 'x'"));
                break;
            case 'a': case 'A':
                // Turning auto OFF is always allowed (safe). Turning it
                // ON requires the controller to have been idle for
                // CONTROLLER_IDLE_MS — prevents arming the arm while a
                // stick is still deflected, which would otherwise cause
                // the very next BT frame to flip auto right back off.
                if (!seqAutoMode && !controllerIdle()) {
                    Serial.println(F("[seq] cannot arm — controller still moving"));
                    break;
                }
                seqAutoMode = !seqAutoMode;
                Serial.print(F("[seq] auto mode "));
                Serial.println(seqAutoMode ? F("ON") : F("OFF"));
                break;
            case 'h': case 'H':
                // Snap targets to home. Slew + watchdog do the rest.
                seqAbort(F("home command"));
                axes[0].target = KF_HOME.base;
                axes[1].target = KF_HOME.shoulder;
                axes[2].target = KF_HOME.elbow;
                axes[3].target = KF_HOME.claw;
                lastFrameMs = millis();
                Serial.println(F("[seq] homing"));
                break;
            case '?':
                Serial.print(F("[seq] auto="));
                Serial.print(seqAutoMode ? F("ON") : F("OFF"));
                Serial.print(F(" state="));
                Serial.print((uint8_t)seqState);
                Serial.print(F(" idx="));
                Serial.print(seqIndex);
                Serial.print(F(" atHome="));
                Serial.println(seqAtHome() ? F("yes") : F("no"));
                break;
            default:
                break;  // ignore — newlines, whitespace, typos
        }
    }

    // 1d. Advance the pickup sequence. No-op when IDLE.
    seqTick();

    // 2. Every TICK_MS, slew the servos one step toward their targets.
    uint32_t now = millis();
    if (now - lastTickMs >= TICK_MS) {
        uint32_t dt = now - lastTickMs;   // actual elapsed time, used by slewAndWrite
        lastTickMs = now;

        // Link watchdog: if we haven't heard a valid frame for too long,
        // pretend the target is wherever we currently are. The slew step
        // then has zero error, so the arm stops mid-motion instead of
        // sailing on toward the last received target.
        if (now - lastFrameMs > LINK_TIMEOUT_MS) {
            for (auto& a : axes) a.target = (uint8_t)(a.current + 0.5f);
        }

        slewAndWrite(dt);
    }
    // Note: nothing else runs in loop(), so this is a tight poll. If you
    // ever add work here, keep it short — anything > a few ms eats into
    // the tick budget and motion gets jerky.
}
